### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by naveen246** [slatedb/slatedb-go#11]
Ref: https://github.com/slatedb/slatedb/issues/90

There is no logging currently in the project.
maybe use Go's default structured log - https://pkg.go.dev/log/slog ?

**Comment by abuzaforfagun** [comment]
I am interested in fixing this issue. What do you think about zap - [https://github.com/uber-go/zap](https://github.com/uber-go/zap)

**Comment by naveen246** [comment]
Thanks for your interest :) 
We can use zap. Please go ahead.

**Comment by naveen246** [comment]
In progress https://github.com/slatedb/slatedb-go/pull/23
