### ISSUE TITLE
Get does not return ErrKeyNotFound when reading a key that is never added

### ISSUE THREAD

**Issue by jayaprabhakar** [slatedb/slatedb-go#51]
I reran FizzBee generated tests. I noticed a regression.

For this sequence of operations
```
Put("k0", "v0")
FlushWAL()
FlushMemtableToL0()
Get("k1")
```
The Get should return an err == ErrKeyNotFound ("key not found")
But Get returns an empty error.

A simple reproduction steps.
```
db.Put([]byte("key1"), []byte("value1"))
db.FlushWAL()
db.FlushMemtableToL0()
data, err := db.Get([]byte("key2"))
if err == nil {
	panic("expected error")
}
```

Looking at the code, this seems to happen at line db.go:180. When !ok, it doesn't return an error but tries to reuse the old err variable which is obviously nil (because the steps before it ha
```
iter, err := sstable.NewIteratorAtKey(&sst, key, db.tableStore.Clone(), 1, 1)
if err != nil {
	return nil, err
}
kv, ok := iter.NextEntry()
if !ok {
	return nil, err       // err here is always nil
}
```

**Comment by naveen246** [comment]
@jayaprabhakar this is fixed with https://github.com/slatedb/slatedb-go/pull/53

**Comment by jayaprabhakar** [comment]
I reran the tests, and all passed. Thanks.
